server:
  port:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id:customers
          uri:lb://customers/**
          predicates:
            - Path:/customers/**

        - id: employees
          uri: lb://employees
          predicates:
            - Path:/employees/**

logging:
  level:
    org.springframework.cloud.gateway: debug